export const PATHNAME = {
  SPLASHSCREEN: 'SplashScreen',
  LOGINSCREEN: 'LoginScreen',
  REGISTERsCREEN: 'RegisterScreen',
  HEARTSCREEN: 'HeartScreen',
  MERCHENTSCREEN: 'MerchentScreen',
  HOMESCREEN: 'HomeScreen',
  NOTIFICATIONSCREEN: 'NotificationScreen',
  SETTINGSCREEN: 'SettingScreen',
  CARTSCREEN: 'CartScreen',
  CHANGEADDRESSSCREEN: 'ChangeAddresscreen',
  CHANGINFOUSERSCREEN: 'ChangeInfoUserScreen',
  CHANGEPASSWORDSCREEN: 'ChangePasswordScreen',
  CHANGECOLORSYSTEMSCREEN: 'ChangeColorSystemScreen',
  INFOSHOPSCREEN: 'InfoShopScreen',
  ORDERSCREEN: 'OrderScreen',
  DETAILADDRESSSCREEN: 'DetailAddressScreen',
  PROFILESCREEN: 'ProfileScreen',
  NEWANDEDITADDRESSSCREEN: 'NewAndEditAddress',
  CATEGORIESSCREEN: 'CategoriesScreen',
  RESETPASSWORDSCREEN: 'ScreenResetPassword',
  PAYMENTSSCREEN: 'PaymentsScreen',
  CONDITIONSCREEN: 'ConditionScreen',
  PRODUCTDETAILSCREEN: 'DetailProductScreen',
  DETAILORDERSCREEN: 'DetailOrderScreen',
};
