export const PATHNAME = {
  SPLASHSCREEN: 'SplashScreen',
  LOGINSCREEN: 'LoginScreen',
  REGISTERsCREEN: 'RegisterScreen',
  HEARTSCREEN: 'HeartScreen',
  MERCHENTSCREEN: 'MerchentScreen',
  HOMESCREEN: 'HomeScreen',
  NOTIFICATIONSCREEN: 'NotificationScreen',
  SETTINGSCREEN: 'SettingScreen',
  CARTSCREEN: 'CartScreen',
  CHANGEADDRESSCREEN: 'ChangeAddresscreen',
  CHANGINFOUSERCREEN: 'ChangeInfoUserScreen',
  CHANGEPASSWORDCREEN: 'ChangePasswordScreen',
  CHANGECOLORSYSTEMCREEN: 'ChangeColorSystemScreen',
  INFOSHOPCREEN: 'InfoShopScreen',
  ORDERCREEN: 'OrderScreen',
  PRODUCT_DETAIL: (id?: string) => `/product/${id ?? ':roldId'}}`,
};
